// This file is generated by scripts/generate-ts.mjs from proto/*.proto.
// Do not edit by hand: run `yarn generate` in brewblox-proto instead.

import {
  AnalogCompareOp,
  AnalogSensorType,
  BlockOrIntfType,
  BlockType,
  ChannelCapabilities,
  DigitalCompareOp,
  DigitalState,
  DisplayTempUnit,
  DS2408ConnectMode,
  FilterChoice,
  GpioDeviceType,
  GpioErrorFlags,
  GpioPins,
  LogicResult,
  PwmFrequency,
  ReferenceKind,
  ResetReason,
  SensorCombiFunc,
  SequenceError,
  SequenceStatus,
  SequenceStoreMode,
  SettingMode,
  Spark2Hardware,
  SparkPlatform,
  TempSensorAnalogSpec,
  TempSensorAnalogType,
  ToggleBehavior,
  TouchCalibrated,
  TransitionDurationPreset,
  ValveState,
  WifiCipherType,
  WifiSecurityType,
} from './spark-block-enums';

// #region Block
export interface Block {
  id: string;
  nid?: number;
  serviceId: string;
  type: BlockType;
  data: { [k: string]: any };
  meta?: { [k: string]: any };
}
// #endregion Block

// #region BloxField
export interface BloxField {
  __bloxtype: string;
}

export interface Quantity extends BloxField {
  __bloxtype: 'Quantity';
  value: number | null;
  unit: string;
  readonly?: boolean;
}

export interface Link extends BloxField {
  __bloxtype: 'Link';
  id: string | null;
  type: BlockOrIntfType | null;
}
// #endregion BloxField

// #region DateString
export type DateString = string;
// #endregion DateString

// #region IoChannel
export interface IoChannel {
  id: Readonly<number>;
  capabilities: Readonly<ChannelCapabilities>;
  claimedBy: Readonly<Link>;
}

export interface IoArrayInterfaceBlock extends Block {
  data: {
    channels: IoChannel[];
  };
}

export interface IoClaimerInterfaceBlock extends Block {
  data: {
    hwDevice: Link;
    channel: number;
  };
}
// #endregion IoChannel

// #region AnalogChannel
export interface AnalogModuleChannel {
  id: Readonly<number>;
  sensorType: Readonly<AnalogSensorType>;
  claimedBy: Readonly<Link>;
  resistance?: Readonly<Quantity>;
  leadResistance?: Readonly<Quantity>;
  bridgeResistance?: Readonly<Quantity>;
  bridgeOutput?: Readonly<number>;
}

export interface AnalogArrayInterfaceBlock extends Block {
  data: {
    analogChannels: AnalogModuleChannel[];
  };
}

export interface AnalogClaimerInterfaceBlock extends Block {
  data: {
    analogDevice: Link;
    analogChannel: number;
  };
}
// #endregion AnalogChannel

// #region EnablerInterfaceBlock
export interface EnablerInterfaceBlock extends Block {
  data: {
    enabled: boolean;
  };
}
// #endregion EnablerInterfaceBlock

// #region ClaimableInterfaceBlock
export interface ClaimableInterfaceBlock extends Block {
  data: {
    claimedBy: Readonly<Link>;
    settingMode: SettingMode;
  };
}
// #endregion ClaimableInterfaceBlock

// #region AnalogConstraints
export interface AnalogConstraintBase {
  enabled: boolean;
  limiting: Readonly<boolean>;
}

export interface ValueConstraint {
  value: number;
  enabled: boolean; // Generic for analog constraints
  limiting: Readonly<boolean>;
}

export interface BalancedConstraint {
  balancerId: Link;
  granted: Readonly<number>;
  enabled: boolean; // Generic for analog constraints
  limiting: Readonly<boolean>;
}

export interface AnalogConstraints {
  min?: ValueConstraint;
  max?: ValueConstraint;
  balanced?: BalancedConstraint;
}
// #endregion AnalogConstraints

// #region DigitalConstraints
export interface DigitalConstraintBase {
  enabled: boolean;
  limiting: Readonly<boolean>;
  remaining: Readonly<Quantity>;
}

export interface DurationConstraint {
  duration: Quantity;
  enabled: boolean; // Generic for digital constraints
  limiting: Readonly<boolean>;
  remaining: Readonly<Quantity>;
}

export interface MutexedConstraint {
  mutexId: Link;
  extraHoldTime: Quantity;
  hasLock: Readonly<boolean>;
  enabled: boolean; // Generic for digital constraints
  limiting: Readonly<boolean>;
  remaining: Readonly<Quantity>;
}

export interface DigitalConstraints {
  minOff?: DurationConstraint;
  minOn?: DurationConstraint;
  delayedOff?: DurationConstraint;
  delayedOn?: DurationConstraint;
  mutexed?: MutexedConstraint;
}
// #endregion DigitalConstraints

// #region DeprecatedConstraints
export interface DeprecatedMinConstraint {
  limiting: Readonly<boolean>;
  min: number;
}

export interface DeprecatedMaxConstraint {
  limiting: Readonly<boolean>;
  max: number;
}

export interface DeprecatedBalancedConstraint {
  limiting: Readonly<boolean>;
  balanced: {
    balancerId: Link;
    granted: number;
  };
}

export interface DeprecatedMinOnConstraint {
  remaining: Readonly<Quantity>;
  minOn: Quantity;
}

export interface DeprecatedMinOffConstraint {
  remaining: Readonly<Quantity>;
  minOff: Quantity;
}

export interface DeprecatedMutexedConstraint {
  remaining: Readonly<Quantity>;
  mutexed: {
    mutexId: Link;
    extraHoldTime: Quantity;
    hasLock: boolean;
  };
}

export interface DeprecatedDelayedOnConstraint {
  remaining: Readonly<Quantity>;
  delayedOn: Quantity;
}

export interface DeprecatedDelayedOffConstraint {
  remaining: Readonly<Quantity>;
  delayedOff: Quantity;
}

export type DeprecatedAnalogConstraint =
  | DeprecatedMinConstraint
  | DeprecatedMaxConstraint
  | DeprecatedBalancedConstraint;

export type DeprecatedDigitalConstraint =
  | DeprecatedMutexedConstraint
  | DeprecatedMinOnConstraint
  | DeprecatedMinOffConstraint
  | DeprecatedDelayedOnConstraint
  | DeprecatedDelayedOffConstraint;

export interface DeprecatedAnalogConstraintsObj {
  constraints: DeprecatedAnalogConstraint[];
}

export interface DeprecatedDigitalConstraintsObj {
  constraints: DeprecatedDigitalConstraint[];
}
// #endregion DeprecatedConstraints

// #region ActuatorAnalogMock
export interface ActuatorAnalogMockBlock extends Block {
  type: 'ActuatorAnalogMock';
  data: {
    enabled: boolean;
    // Written without settingMode, it also sets the mode to STORED, unless the
    // block is claimed.
    storedSetting: number;
    desiredSetting: Readonly<number | null>;
    setting: Readonly<number | null>;
    value: Readonly<number | null>;
    minSetting: number;
    maxSetting: number;
    minValue: number;
    maxValue: number;
    constraints: AnalogConstraints;
    claimedBy: Readonly<Link>;
    settingMode: SettingMode;
  };
}
// #endregion ActuatorAnalogMock

// #region ActuatorLogic
export interface DigitalCompare {
  op: DigitalCompareOp;
  result: Readonly<LogicResult>;
  id: Link;
  rhs: DigitalState;
}

export interface AnalogCompare {
  op: AnalogCompareOp;
  result: Readonly<LogicResult>;
  id: Link;
  rhs: number;
}

export interface ActuatorLogicBlock extends Block {
  type: 'ActuatorLogic';
  data: {
    targetId: Link;
    enabled: boolean;
    result: Readonly<LogicResult>;
    expression: string; // a-zA-Z&|^!()
    digital: DigitalCompare[]; // a-z
    analog: AnalogCompare[]; // A-Z
    errorPos: Readonly<number>;
  };
}
// #endregion ActuatorLogic

// #region ActuatorOffset
export interface ActuatorOffsetBlock extends Block {
  type: 'ActuatorOffset';
  data: {
    enabled: boolean;
    targetId: Link;
    referenceId: Link;
    // Written without settingMode, it also sets the mode to STORED, unless the
    // block is claimed.
    storedSetting: Quantity;
    desiredSetting: Readonly<Quantity>;
    setting: Readonly<Quantity>;
    value: Readonly<Quantity>;
    referenceSettingOrValue: ReferenceKind;
    constraints: AnalogConstraints;
    claimedBy: Readonly<Link>;
    settingMode: SettingMode;
  };
}
// #endregion ActuatorOffset

// #region ActuatorPwm
export interface ActuatorPwmBlock extends Block {
  type: 'ActuatorPwm';
  data: {
    enabled: boolean;
    actuatorId: Link;
    // Written without settingMode, it also sets the mode to STORED, unless the
    // block is claimed.
    storedSetting: number;
    desiredSetting: Readonly<number | null>;
    setting: Readonly<number | null>;
    value: Readonly<number | null>;
    period: Quantity;
    constraints: AnalogConstraints;
    claimedBy: Readonly<Link>;
    settingMode: SettingMode;
  };
}
// #endregion ActuatorPwm

// #region Balancer
export interface BalancedActuator {
  id: Readonly<Link>;
  requested: Readonly<number>;
  granted: Readonly<number>;
}

export interface BalancerBlock extends Block {
  type: 'Balancer';
  data: {
    clients: Readonly<BalancedActuator[]>;
  };
}
// #endregion Balancer

// #region DeprecatedObject
export interface DeprecatedObjectBlock extends Block {
  type: 'DeprecatedObject';
  data: {
    actualId: Readonly<number>;
  };
}
// #endregion DeprecatedObject

// #region DigitalActuator
export interface DigitalActuatorBlock extends Block {
  type: 'DigitalActuator';
  data: {
    hwDevice: Link; // A new device clears channel, unless the same write sets it.
    channel: number;
    // Written without settingMode, it also sets the mode to STORED, unless the
    // block is claimed.
    storedState: DigitalState;
    desiredState: Readonly<DigitalState | null>;
    state: Readonly<DigitalState | null>;
    invert: boolean;
    constraints: DigitalConstraints;
    transitionDurationPreset: TransitionDurationPreset;
    transitionDurationSetting: Quantity;
    transitionDurationValue: Readonly<Quantity>;
    claimedBy: Readonly<Link>;
    settingMode: SettingMode;
  };
}
// #endregion DigitalActuator

// #region DigitalInput
export interface DigitalInputBlock extends Block {
  type: 'DigitalInput';
  data: {
    hwDevice: Link; // A new device clears channel, unless the same write sets it.
    channel: number;
    state: Readonly<DigitalState | null>;
    invert: boolean;
    behavior: ToggleBehavior;
    minActiveTime: Quantity;
    hwState: Readonly<DigitalState | null>;
  };
}
// #endregion DigitalInput

// #region DisplaySettings
export interface DisplaySlot {
  pos: number; // 1-indexed
  color: string;
  name: string;
  // oneof WidgetType: at most one is set
  tempSensor?: Link;
  setpointSensorPair?: Link;
  actuatorAnalog?: Link;
  pid?: Link;
}

export interface DisplaySettingsBlock extends Block {
  type: 'DisplaySettings';
  data: {
    widgets: DisplaySlot[];
    name: string;
  };
}
// #endregion DisplaySettings

// #region DS2408
export interface DS2408Block extends Block {
  type: 'DS2408';
  data: {
    address: string;
    connected: Readonly<boolean>;
    connectMode: DS2408ConnectMode;
    oneWireBusId: Link; // A write of 0 is ignored.
    // if connectMode is valve, the channels are [1,5]. Each valve uses 4 pins
    // if connectMode is actuator, the channels are [1,2,3,4,5,6,7,8]
    channels: Readonly<IoChannel[]>;
  };
}
// #endregion DS2408

// #region DS2413
export interface DS2413Block extends Block {
  type: 'DS2413';
  data: {
    address: string;
    connected: Readonly<boolean>;
    oneWireBusId: Link; // A write of 0 is ignored.
    channels: Readonly<IoChannel[]>;
  };
}
// #endregion DS2413

// #region FastPwm
export interface FastPwmBlock extends Block {
  type: 'FastPwm';
  data: {
    enabled: boolean;
    hwDevice: Link; // A new device clears channel, unless the same write sets it.
    channel: number;
    // Written without settingMode, it also sets the mode to STORED, unless the
    // block is claimed.
    storedSetting: number;
    desiredSetting: Readonly<number | null>;
    setting: Readonly<number | null>;
    value: Readonly<number | null>;
    invert: boolean;
    frequency: PwmFrequency;
    constraints: AnalogConstraints;
    transitionDurationPreset: TransitionDurationPreset;
    transitionDurationSetting: Quantity;
    transitionDurationValue: Readonly<Quantity>;
    claimedBy: Readonly<Link>;
    settingMode: SettingMode;
  };
}
// #endregion FastPwm

// #region GpioModule
export interface GpioModuleChannel extends IoChannel {
  id: number;
  deviceType: GpioDeviceType;
  pinsMask: GpioPins;
  width: number;
  name: string;
  capabilities: Readonly<ChannelCapabilities>;
  claimedBy: Readonly<Link>;
  errorFlags: Readonly<GpioErrorFlags>;
}

export interface GpioModuleStatus {
  // 7 reserved bit used to signal spi error | 6 overtemperature shutdown | 5
  // overtemperature warning 4 open load | 3 overcurrent | 2 undervoltage
  // lockout | 1 overvoltage | 0 power-on-reset
  moduleStatus: Readonly<GpioErrorFlags>;
  pullUpDesired: Readonly<GpioPins>;
  pullUpStatus: Readonly<GpioPins>;
  pullUpWhenActive: Readonly<GpioPins>;
  pullUpWhenInactive: Readonly<GpioPins>;
  pullDownDesired: Readonly<GpioPins>;
  pullDownStatus: Readonly<GpioPins>;
  pullDownWhenActive: Readonly<GpioPins>;
  pullDownWhenInactive: Readonly<GpioPins>;
  overCurrent: Readonly<GpioPins>;
  openLoad: Readonly<GpioPins>;
  faultsHistory5m: Readonly<GpioErrorFlags>;
  faultsHistory60m: Readonly<GpioErrorFlags>;
}

export interface GpioModuleBlock extends Block {
  type: 'GpioModule';
  data: {
    channels: GpioModuleChannel[];
    modulePosition: number;
    useExternalPower: boolean;
    status: Readonly<GpioModuleStatus>;
    analogChannels: Readonly<AnalogModuleChannel[]>;
    baroPressure?: Readonly<Quantity>;
  };
}
// #endregion GpioModule

// #region InactiveObject
export interface InactiveObjectBlock extends Block {
  type: 'InactiveObject';
  data: {
    actualType: BlockType;
  };
}
// #endregion InactiveObject

// #region MockPins
export interface MockPinsBlock extends Block {
  type: 'MockPins';
  data: {
    channels: Readonly<IoChannel[]>;
  };
}
// #endregion MockPins

// #region MotorValve
export interface MotorValveBlock extends Block {
  type: 'MotorValve';
  data: {
    hwDevice: Link; // A new device clears channel, unless the same write sets it.
    channel: number;
    // Written without settingMode, it also sets the mode to STORED, unless the
    // block is claimed.
    storedState: DigitalState;
    desiredState: Readonly<DigitalState | null>;
    state: Readonly<DigitalState | null>;
    valveState: Readonly<ValveState | null>;
    constraints: DigitalConstraints;
    claimedBy: Readonly<Link>;
    settingMode: SettingMode;
  };
}
// #endregion MotorValve

// #region Mutex
export interface MutexBlock extends Block {
  type: 'Mutex';
  data: {
    waitRemaining: Readonly<Quantity>;
  };
}
// #endregion Mutex

// #region Pid
export interface PidBlock extends Block {
  type: 'Pid';
  data: {
    inputId: Link;
    outputId: Link;
    inputValue: Readonly<Quantity>;
    inputSetting: Readonly<Quantity>;
    outputValue: Readonly<number | null>;
    outputSetting: Readonly<number | null>;
    enabled: boolean;
    active: Readonly<boolean>;
    kp: Quantity;
    ti: Quantity;
    td: Quantity;
    p: Readonly<number | null>;
    i: Readonly<number | null>;
    d: Readonly<number | null>;
    error: Readonly<Quantity>;
    integral: Readonly<number>;
    derivative: Readonly<number>;
    integralReset: number; // when non-zero, resets integral to make i equal to what has been sent
    boilPointAdjust: Quantity;
    boilMinOutput: number;
    boilModeActive: Readonly<boolean>;
    derivativeFilter: Readonly<FilterChoice>;
    derivativeFilterChoice: FilterChoice;
    kff: Quantity;
    ff: Readonly<number | null>;
    ambientId: Link;
    ambientValue: Readonly<Quantity>;
    ambientOffset: Readonly<Quantity>;
    smoothGain: Readonly<number | null>;
    smoothBand: Quantity; // Smoothing band for proportional/derivative blending
  };
}
// #endregion Pid

// #region Sequence
export interface SequenceBlock extends Block {
  type: 'Sequence';
  data: {
    enabled: boolean;
    // A write keeps a running sequence at its active instruction when that
    // instruction is still there and the ones before it keep their opcodes; the
    // active one restarts with its new arguments. Otherwise the sequence restarts
    // at the first instruction, and when the write removed the active one it is
    // also disabled, unless the same write sets enabled.
    instructions: string[];
    variablesId: Link;
    overrideState: boolean;
    activeInstruction: number; // Applies only when the same write sets overrideState.
    storeMode: SequenceStoreMode;
    status: Readonly<SequenceStatus>;
    error: Readonly<SequenceError>;
    elapsed: Readonly<Quantity>;
  };
}
// #endregion Sequence

// #region SetpointProfile
export interface Setpoint {
  time: Quantity; // Offset from start
  temperature: Quantity;
}

export interface SetpointProfileBlock extends Block {
  type: 'SetpointProfile';
  data: {
    points: Setpoint[];
    enabled: boolean;
    targetId: Link;
    setting: Readonly<Quantity>;
    start: DateString | null;
    interpolateDisabled: boolean;
  };
}
// #endregion SetpointProfile

// #region SetpointSensorPair
export interface SetpointSensorPairBlock extends Block {
  type: 'SetpointSensorPair';
  data: {
    enabled: boolean;
    sensorId: Link;
    // Written without settingMode, it also sets the mode to STORED, unless the
    // block is claimed.
    storedSetting: Quantity;
    desiredSetting: Readonly<Quantity>;
    setting: Readonly<Quantity>;
    value: Readonly<Quantity>;
    valueUnfiltered: Readonly<Quantity>;
    filter: FilterChoice;
    filterThreshold: Quantity;
    resetFilter: boolean;
    claimedBy: Readonly<Link>;
    settingMode: SettingMode;
    rampLimitEnabled: boolean;
    rampLimit: Quantity;
    rampDuration: Quantity;
    // Measured sensor update interval.
    // Allows the UI to translate filter choices to 95% step response delays.
    updateInterval: Readonly<Quantity>;
  };
}
// #endregion SetpointSensorPair

// #region Spark2Pins
export interface Spark2PinsBlock extends Block {
  type: 'Spark2Pins';
  data: {
    soundAlarm: boolean;
    hardware: Readonly<Spark2Hardware>;
    channels: Readonly<IoChannel[]>;
  };
}
// #endregion Spark2Pins

// #region Spark3Pins
export interface Spark3PinsBlock extends Block {
  type: 'Spark3Pins';
  data: {
    enableIoSupply5V: boolean;
    enableIoSupply12V: boolean;
    soundAlarm: boolean;
    voltage5: Readonly<number>;
    voltage12: Readonly<number>;
    channels: Readonly<IoChannel[]>;
  };
}
// #endregion Spark3Pins

// #region SysInfo
export interface SysInfoBlock extends Block {
  type: 'SysInfo';
  data: {
    deviceId: Readonly<string>;
    version: Readonly<string>;
    platform: Readonly<SparkPlatform>;
    protocolVersion: Readonly<string>;
    releaseDate: Readonly<string>;
    protocolDate: Readonly<string>;
    ip: Readonly<string>;
    uptime: Readonly<Quantity>;
    updatesPerSecond: Readonly<number>;
    systemTime: DateString | null;
    timeZone: string;
    tempUnit: DisplayTempUnit;
    displayBrightness: number;
    voltage5: Readonly<number>;
    voltageExternal: Readonly<number>;
    memoryFree: Readonly<number>;
    memoryFreeContiguous: Readonly<number>;
    memoryFreeLowest: Readonly<number>;
    mainTaskStackFreeLowest: Readonly<number>;
    resetReason: Readonly<ResetReason>;
    // Temperature of the controller's own chip, from its internal sensor. Null
    // on a platform without one, or when the read fails.
    chipTemperature: Readonly<Quantity>;
  };
}
// #endregion SysInfo

// #region TempSensorAnalog
export interface TempSensorAnalogBlock extends Block {
  type: 'TempSensorAnalog';
  data: {
    sensorType: TempSensorAnalogType;
    analogDevice: Link;
    analogChannel: number;
    value: Readonly<Quantity>;
    detected: Readonly<AnalogSensorType>;
    spec: TempSensorAnalogSpec;
    resistance?: Readonly<Quantity>;
    spec_r0?: Readonly<Quantity>;
    spec_a?: Readonly<number>;
    spec_b?: Readonly<number>;
    spec_c?: Readonly<number>;
    spec_r0_override?: Quantity;
    spec_a_override?: number;
    spec_b_override?: number;
    spec_c_override?: number;
  };
}
// #endregion TempSensorAnalog

// #region TempSensorCombi
export interface TempSensorCombiBlock extends Block {
  type: 'TempSensorCombi';
  data: {
    value: Readonly<Quantity>;
    combineFunc: SensorCombiFunc;
    sensors: Link[];
  };
}
// #endregion TempSensorCombi

// #region TempSensorExternal
export interface TempSensorExternalBlock extends Block {
  type: 'TempSensorExternal';
  data: {
    enabled: boolean;
    timeout: Quantity;
    // Counts only with the time it arrived: a setting written before the
    // controller's clock is set has no value until the next one. The service
    // sets the clock on connect.
    setting: Quantity;
    lastUpdated: Readonly<DateString | null>;
    value: Readonly<Quantity>;
  };
}
// #endregion TempSensorExternal

// #region TempSensorMock
export interface Fluctuation {
  amplitude: Quantity;
  period: Quantity;
}

export interface TempSensorMockBlock extends Block {
  type: 'TempSensorMock';
  data: {
    value: Readonly<Quantity>;
    connected: boolean;
    setting: Quantity;
    fluctuations: Fluctuation[];
  };
}
// #endregion TempSensorMock

// #region TempSensorOneWire
export interface TempSensorOneWireBlock extends Block {
  type: 'TempSensorOneWire';
  data: {
    value: Readonly<Quantity>;
    offset: Quantity;
    address: string;
    oneWireBusId: Link; // A write of 0 is ignored.
  };
}
// #endregion TempSensorOneWire

// #region TouchSettings
export interface TouchSettingsBlock extends Block {
  type: 'TouchSettings';
  data: {
    calibrated: TouchCalibrated;
    xOffset: number;
    yOffset: number;
    xBitsPerPixelX16: number;
    yBitsPerPixelX16: number;
  };
}
// #endregion TouchSettings

// #region Variables
export type VarContainer =
  | { empty: boolean }
  | { digital: DigitalState }
  | { analog: number }
  | { temp: Quantity }
  | { deltaTemp: Quantity }
  | { timestamp: DateString | null }
  | { duration: Quantity }
  | { link: Link };

export interface VariablesBlock extends Block {
  type: 'Variables';
  data: {
    // A write merges by key: the keys it carries replace their entries, an
    // `empty` entry deletes its key, and the other keys are kept; present but
    // empty changes nothing. A create or a stored record is the whole map.
    variables: { [key: string]: VarContainer };
  };
}
// #endregion Variables

// #region WiFiSettings
export interface WiFiSettingsBlock extends Block {
  type: 'WiFiSettings';
  data: {
    // Read: the network joined, absent while not connected.
    // Write: the network to join, together with the password.
    ssid: string;
    // Write-only, never read back. A write with a password applies ssid,
    // security and cipher with it, absent ones as empty or unsecured; a write
    // without one applies none of them.
    password: string;
    security: WifiSecurityType;
    cipher: WifiCipherType;
    signal: Readonly<number>; // dBm
  };
}
// #endregion WiFiSettings
