syntax = "proto3";

import "brewblox.proto";
import "nanopb.proto";
import "Constraints.proto";
import "Claims.proto";

package blox.ActuatorPwm;

message Block {
  option (brewblox.msg).objtype = ActuatorPwm;
  option (brewblox.msg).impl = ProcessValueInterface;
  option (brewblox.msg).impl = ActuatorAnalogInterface;
  option (brewblox.msg).impl = StoredAnalogInterface;
  option (brewblox.msg).impl = EnablerInterface;
  option (brewblox.msg).impl = ClaimableInterface;

  bool enabled = 8 [ (brewblox.field).stored = true ];

  uint32 actuatorId = 1 [
    (brewblox.field).objtype = ActuatorDigitalInterface,
    (brewblox.field).stored = true
  ];

  sint32 storedSetting = 11 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).stored = true,
    (nanopb).int_size = IS_32
  ];
  sint32 desiredSetting = 9 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];
  sint32 setting = 4 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];
  sint32 value = 5 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  uint32 period = 3 [
    (brewblox.field).unit = Second,
    (brewblox.field).scale = 1000,
    (brewblox.field).stored = true
  ];
  Constraints.DeprecatedAnalogConstraints constrainedBy = 6;
  Constraints.AnalogConstraints constraints = 13
      [ (brewblox.field).stored = true ];

  uint32 claimedBy = 10
      [ (brewblox.field).objtype = Any, (brewblox.field).readonly = true ];
  Claims.SettingMode settingMode = 12 [ (brewblox.field).stored = true ];

  // Deprecated field
  bool drivenActuatorId = 90
      [ (brewblox.field).ignored = true, (nanopb).type = FT_IGNORE ];
}
