syntax = "proto3";

import "brewblox.proto";
import "nanopb.proto";
import "IoArray.proto";

package blox.DigitalInput;

enum ToggleBehavior {
  DIRECT = 0;
  ALTERNATING = 1;
};

message Block {
  option (brewblox.msg).objtype = DigitalInput;
  option (brewblox.msg).impl = DigitalInterface;
  option (brewblox.msg).impl = IoClaimerInterface;

  // A new device clears channel, unless the same write sets it.
  optional uint32 hwDevice = 1 [
    (brewblox.field).objtype = IoArrayInterface,
    (brewblox.field).stored = true
  ];
  optional uint32 channel = 2
      [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];

  optional IoArray.DigitalState state = 3
      [ (brewblox.field).logged = true, (brewblox.field).readonly = true ];

  optional bool invert = 4 [ (brewblox.field).stored = true ];
  optional ToggleBehavior behavior = 5 [ (brewblox.field).stored = true ];
  optional uint32 minActiveTime = 6 [
    (brewblox.field).unit = Second,
    (brewblox.field).scale = 1000,
    (brewblox.field).stored = true
  ];
  optional IoArray.DigitalState hwState = 7
      [ (brewblox.field).readonly = true ];
}
