syntax = "proto3";

import "brewblox.proto";
import "nanopb.proto";

package blox.DisplaySettings;

enum VolumeDisplayMode {
  VOLUME_DISPLAY_MODE_HEIGHT = 0;
  VOLUME_DISPLAY_MODE_VOLUME = 1;
  VOLUME_DISPLAY_MODE_VOLUME_SINCE_TARE = 2;
  VOLUME_DISPLAY_MODE_HEIGHT_SINCE_TARE = 3;
  VOLUME_DISPLAY_MODE_TARE_BUTTON = 4;
  VOLUME_DISPLAY_MODE_LIVE_BUTTON = 5;
}

message VolumeWidget {
  uint32 volumeSensor = 1 [
    (brewblox.field).objtype = VolumeSensor,
    (brewblox.field).stored = true
  ];
  VolumeDisplayMode displayMode = 2 [ (brewblox.field).stored = true ];
}

message Widget {
  uint32 pos = 1 [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];
  bytes color = 2 [
    (brewblox.field).hexstr = true,
    (brewblox.field).stored = true,
    (nanopb).max_size = 3,
    (nanopb).fixed_length = true
  ];
  string name = 3 [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  oneof WidgetType {
    uint32 tempSensor = 10 [
      (brewblox.field).objtype = TempSensorInterface,
      (brewblox.field).stored = true
    ];
    uint32 setpointSensorPair = 11 [
      (brewblox.field).objtype = SetpointSensorPairInterface,
      (brewblox.field).stored = true
    ];
    uint32 actuatorAnalog = 12 [
      (brewblox.field).objtype = ActuatorAnalogInterface,
      (brewblox.field).stored = true
    ];
    uint32 pid = 14
        [ (brewblox.field).objtype = Pid, (brewblox.field).stored = true ];
    VolumeWidget volumeSensor = 15 [ (brewblox.field).stored = true ];
  };
}

message Block {
  option (brewblox.msg).objtype = DisplaySettings;

  repeated Widget widgets = 1
      [ (brewblox.field).stored = true, (nanopb).max_count = 6 ];
  string name = 2 [ (brewblox.field).stored = true, (nanopb).max_size = 40 ];

  // Deprecated fields
  bool brightness = 90
      [ (brewblox.field).ignored = true, (nanopb).type = FT_IGNORE ];
  bool timeZone = 91
      [ (brewblox.field).ignored = true, (nanopb).type = FT_IGNORE ];
  bool tempUnit = 92
      [ (brewblox.field).ignored = true, (nanopb).type = FT_IGNORE ];
}
