syntax = "proto3";

import "brewblox.proto";
import "nanopb.proto";
import "SetpointSensorPair.proto";

package blox.Pid;

message Block {
  option (brewblox.msg).objtype = Pid;
  option (brewblox.msg).impl = EnablerInterface;

  uint32 inputId = 1 [
    (brewblox.field).objtype = SetpointSensorPairInterface,
    (brewblox.field).stored = true
  ];
  uint32 outputId = 2 [
    (brewblox.field).objtype = ActuatorAnalogInterface,
    (brewblox.field).stored = true
  ];

  sint32 inputValue = 5 [
    (brewblox.field).unit = Celsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];
  sint32 inputSetting = 6 [
    (brewblox.field).unit = Celsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];
  sint32 outputValue = 7 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];
  sint32 outputSetting = 8 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  bool enabled = 11
      [ (brewblox.field).stored = true, (brewblox.field).logged = true ];
  bool active = 12
      [ (brewblox.field).logged = true, (brewblox.field).readonly = true ];

  sint32 kp = 13 [
    (brewblox.field).unit = InverseCelsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).stored = true,
    (nanopb).int_size = IS_32
  ];
  uint32 ti = 14 [
    (brewblox.field).unit = Second,
    (brewblox.field).stored = true,
    (nanopb).int_size = IS_16
  ];
  uint32 td = 15 [
    (brewblox.field).unit = Second,
    (brewblox.field).stored = true,
    (nanopb).int_size = IS_16
  ];

  sint32 p = 16 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];
  sint32 i = 17 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];
  sint32 d = 18 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  sint32 error = 19 [
    (brewblox.field).unit = DeltaCelsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];
  sint32 integral = 20 [
    (brewblox.field).scale = 256,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  sint32 derivative = 21 [
    (brewblox.field).scale = 524288,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  // when non-zero, resets integral to make i equal to what has been sent
  sint32 integralReset = 23 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (nanopb).int_size = IS_32
  ];

  sint32 boilPointAdjust = 24 [
    (brewblox.field).unit = DeltaCelsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).stored = true,
    (nanopb).int_size = IS_32
  ];
  sint32 boilMinOutput = 25 [
    (brewblox.field).scale = 4096,
    (brewblox.field).stored = true,
    (nanopb).int_size = IS_32
  ];
  bool boilModeActive = 26
      [ (brewblox.field).logged = true, (brewblox.field).readonly = true ];

  SetpointSensorPair.FilterChoice derivativeFilter = 27
      [ (brewblox.field).readonly = true ];

  SetpointSensorPair.FilterChoice derivativeFilterChoice = 28
      [ (brewblox.field).stored = true ];

  sint32 kff = 29 [
    (brewblox.field).unit = InverseCelsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).stored = true,
    (nanopb).int_size = IS_32
  ];

  sint32 ff = 30 [
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  uint32 ambientId = 31 [
    (brewblox.field).objtype = TempSensorInterface,
    (brewblox.field).stored = true
  ];

  sint32 ambientValue = 32 [
    (brewblox.field).unit = Celsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  sint32 ambientOffset = 33 [
    (brewblox.field).unit = DeltaCelsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  // Smoothing band for proportional/derivative blending
  sint32 smoothBand = 34 [
    (brewblox.field).unit = DeltaCelsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).stored = true,
    (nanopb).int_size = IS_32
  ];

  // Deprecated field
  bool drivenOutputId = 90
      [ (brewblox.field).ignored = true, (nanopb).type = FT_IGNORE ];
}
