syntax = "proto3";

import "nanopb.proto";
import "brewblox.proto";

package screen;

message LayoutNode {
  enum Type {
    Row = 0;
    Column = 1;
    Content = 2;
  }

  uint32 parent = 1
      [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];
  uint32 nodeId = 2
      [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];
  Type type = 3 [ (brewblox.field).stored = true ];
  uint32 weight = 4
      [ (brewblox.field).stored = true, (nanopb).int_size = IS_16 ];
}

message Color {
  uint32 r = 1 [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];
  uint32 g = 2 [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];
  uint32 b = 3 [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];
}

message NumericValueWidget {
  Color color = 1 [ (brewblox.field).stored = true ];
  uint32 value = 2 [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];
  string label = 3 [ (brewblox.field).stored = true, (nanopb).max_length = 40 ];
}

message ColorWidget { Color color = 1 [ (brewblox.field).stored = true ]; }

message ContentNode {
  uint32 layoutNodeId = 1
      [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];
  oneof content {
    NumericValueWidget numericValueWidget = 2
        [ (brewblox.field).stored = true ];
    ColorWidget colorWidget = 3 [ (brewblox.field).stored = true ];
  }
}

message Config {
  repeated LayoutNode layoutNodes = 1 [ (brewblox.field).stored = true ];
  repeated ContentNode contentNodes = 2 [ (brewblox.field).stored = true ];
}
