syntax = "proto3";

import "brewblox.proto";
import "nanopb.proto";
import "IoArray.proto";

package blox.Sequence;

message Comment { string text = 1 [ (brewblox.field).stored = true ]; }

message Restart {}

message EnableDisable {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = EnablerInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 2
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message Wait {}

message WaitDuration {
  oneof duration {
    uint32 __raw__duration = 1 [
      (brewblox.field).unit = Second,
      (brewblox.field).stored = true,
      (nanopb).int_size = IS_32
    ];
    string __var__duration = 2
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message WaitUntil {
  oneof time {
    uint32 __raw__time = 1 [
      (brewblox.field).datetime = true,
      (brewblox.field).stored = true,
      (nanopb).int_size = IS_32
    ];
    string __var__time = 2
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message WaitTemperatureRange {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = TempSensorInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 4
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }

  oneof lower {
    sint32 __raw__lower = 2 [
      (brewblox.field).unit = Celsius,
      (brewblox.field).scale = 4096,
      (brewblox.field).stored = true,
      (nanopb).int_size = IS_32
    ];
    string __var__lower = 5
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }

  oneof upper {
    sint32 __raw__upper = 3 [
      (brewblox.field).unit = Celsius,
      (brewblox.field).scale = 4096,
      (brewblox.field).stored = true,
      (nanopb).int_size = IS_32
    ];
    string __var__upper = 6
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message WaitTemperatureBoundary {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = TempSensorInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 3
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }

  oneof value {
    sint32 __raw__value = 2 [
      (brewblox.field).unit = Celsius,
      (brewblox.field).scale = 4096,
      (brewblox.field).stored = true,
      (nanopb).int_size = IS_32
    ];
    string __var__value = 4
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message SetSetpoint {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = SetpointSensorPairInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 3
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }

  oneof setting {
    sint32 __raw__setting = 2 [
      (brewblox.field).unit = Celsius,
      (brewblox.field).scale = 4096,
      (brewblox.field).stored = true,
      (nanopb).int_size = IS_32
    ];
    string __var__setting = 4
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message WaitSetpoint {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = SetpointSensorPairInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 3
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }

  oneof precision {
    sint32 __raw__precision = 2 [
      (brewblox.field).unit = DeltaCelsius,
      (brewblox.field).scale = 4096,
      (brewblox.field).stored = true,
      (nanopb).int_size = IS_32
    ];
    string __var__precision = 4
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message SetDigital {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = ActuatorDigitalInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 3
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }

  oneof setting {
    IoArray.DigitalState __raw__setting = 2 [ (brewblox.field).stored = true ];
    string __var__setting = 4
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message WaitDigital {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = ActuatorDigitalInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 2
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message WaitDigitalState {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = DigitalInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 3
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }

  oneof state {
    IoArray.DigitalState __raw__state = 2 [ (brewblox.field).stored = true ];
    string __var__state = 4
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message SetPwm {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = ActuatorAnalogInterface,
      (brewblox.field).stored = true
    ];
    string __var__target = 3
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }

  oneof setting {
    sint32 __raw__setting = 2 [
      (brewblox.field).scale = 4096,
      (brewblox.field).stored = true,
      (nanopb).int_size = IS_32
    ];
    string __var__setting = 4
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message TargetProfile {
  oneof target {
    uint32 __raw__target = 1 [
      (brewblox.field).objtype = SetpointProfile,
      (brewblox.field).stored = true
    ];
    string __var__target = 2
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message TargetSequence {
  oneof target {
    uint32 __raw__target = 1
        [ (brewblox.field).objtype = Sequence, (brewblox.field).stored = true ];
    string __var__target = 2
        [ (brewblox.field).stored = true, (nanopb).max_size = 16 ];
  }
}

message Instruction {
  option (nanopb_msgopt).submsg_callback = true;

  oneof instruction {
    Restart RESTART = 1 [ (brewblox.field).stored = true ];
    EnableDisable ENABLE = 2 [ (brewblox.field).stored = true ];
    EnableDisable DISABLE = 3 [ (brewblox.field).stored = true ];
    Wait WAIT = 20 [ (brewblox.field).stored = true ];
    WaitDuration WAIT_DURATION = 4 [ (brewblox.field).stored = true ];
    WaitUntil WAIT_UNTIL = 5 [ (brewblox.field).stored = true ];
    WaitTemperatureRange WAIT_TEMP_BETWEEN = 6
        [ (brewblox.field).stored = true ];
    WaitTemperatureRange WAIT_TEMP_NOT_BETWEEN = 7
        [ (brewblox.field).stored = true ];
    WaitTemperatureRange WAIT_TEMP_UNEXPECTED = 8
        [ (brewblox.field).stored = true ];
    WaitTemperatureBoundary WAIT_TEMP_ABOVE = 9
        [ (brewblox.field).stored = true ];
    WaitTemperatureBoundary WAIT_TEMP_BELOW = 10
        [ (brewblox.field).stored = true ];
    SetSetpoint SET_SETPOINT = 11 [ (brewblox.field).stored = true ];
    WaitSetpoint WAIT_SETPOINT = 12 [ (brewblox.field).stored = true ];
    WaitSetpoint WAIT_SETPOINT_ABOVE = 21 [ (brewblox.field).stored = true ];
    WaitSetpoint WAIT_SETPOINT_BELOW = 22 [ (brewblox.field).stored = true ];
    SetDigital SET_DIGITAL = 13 [ (brewblox.field).stored = true ];
    WaitDigital WAIT_DIGITAL = 14 [ (brewblox.field).stored = true ];
    WaitDigitalState WAIT_DIGITAL_EQUALS = 23
        [ (brewblox.field).stored = true ];
    SetPwm SET_PWM = 15 [ (brewblox.field).stored = true ];
    TargetProfile START_PROFILE = 16 [ (brewblox.field).stored = true ];
    TargetProfile WAIT_PROFILE = 17 [ (brewblox.field).stored = true ];
    TargetSequence START_SEQUENCE = 18 [ (brewblox.field).stored = true ];
    TargetSequence WAIT_SEQUENCE = 19 [ (brewblox.field).stored = true ];

    // Special case: comment lines start with #
    Comment COMMENT = 200 [ (brewblox.field).stored = true ];
  }
}

enum SequenceStatus {
  UNKNOWN = 0;
  DISABLED = 1;
  PAUSED = 2;
  NEXT = 3;
  WAIT = 4;
  END = 5;
  RESTART = 6;
  ERROR = 7;
}

enum SequenceError {
  NONE = 0;
  INVALID_ARGUMENT = 1;
  INVALID_TARGET = 2;
  INACTIVE_TARGET = 3;
  DISABLED_TARGET = 4;
  SYSTEM_TIME_NOT_AVAILABLE = 5;
  VARIABLES_NOT_SUPPORTED = 6;
  UNDEFINED_VARIABLE = 7;
  INVALID_VARIABLE = 8;
}

enum SequenceStoreMode {
  AT_RESTORE_INSTRUCTION_RESTORE_ENABLED = 0;
  AT_RESTORE_INSTRUCTION_ALWAYS_ENABLED = 1;
  AT_RESTORE_INSTRUCTION_NEVER_ENABLED = 2;
  AT_FIRST_INSTRUCTION_RESTORE_ENABLED = 3;
  AT_FIRST_INSTRUCTION_ALWAYS_ENABLED = 4;
  AT_FIRST_INSTRUCTION_NEVER_ENABLED = 5;
}

message Block {
  option (brewblox.msg).objtype = Sequence;
  option (brewblox.msg).impl = EnablerInterface;

  bool enabled = 1
      [ (brewblox.field).stored = true, (brewblox.field).logged = true ];
  repeated Instruction instructions = 2 [ (brewblox.field).stored = true ];
  uint32 variablesId = 11
      [ (brewblox.field).objtype = Variables, (brewblox.field).stored = true ];

  bool overrideState = 3 [ (brewblox.field).stored = true ];
  uint32 activeInstruction = 4 [
    (brewblox.field).stored = true,
    (brewblox.field).logged = true,
    (nanopb).int_size = IS_16
  ];

  SequenceStoreMode storeMode = 12 [ (brewblox.field).stored = true ];

  SequenceStatus status = 8 [ (brewblox.field).readonly = true ];
  SequenceError error = 9 [ (brewblox.field).readonly = true ];

  uint32 elapsed = 10 [
    (brewblox.field).unit = Second,
    (brewblox.field).scale = 1000,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  // Deprecated fields
  uint32 activeInstructionStartedAt = 5
      [ (brewblox.field).ignored = true, (nanopb).type = FT_IGNORE ];
  uint32 disabledAt = 6
      [ (brewblox.field).ignored = true, (nanopb).type = FT_IGNORE ];
  uint32 disabledDuration = 7
      [ (brewblox.field).ignored = true, (nanopb).type = FT_IGNORE ];
}
