syntax = "proto3";

import "brewblox.proto";
import "nanopb.proto";
import "GpioModule.proto";

package blox.TempSensorAnalog;

enum TempSensorAnalogType {
  TEMP_SENSOR_TYPE_NOT_SET = 0;
  TEMP_SENSOR_TYPE_RTD_2WIRE = 1;
  TEMP_SENSOR_TYPE_RTD_3WIRE = 2;
  TEMP_SENSOR_TYPE_RTD_4WIRE = 3;
}

enum TempSensorAnalogSpec {
  SPEC_NOT_SET = 0;
  SPEC_PT100_385 = 1;
  SPEC_PT100_392 = 2;
  SPEC_PT1000_385 = 3;
  SPEC_PT1000_392 = 4;
}

message Block {
  option (brewblox.msg).objtype = TempSensorAnalog;
  option (brewblox.msg).impl = TempSensorInterface;
  option (brewblox.msg).impl = AnalogClaimerInterface;

  TempSensorAnalogType sensorType = 1 [ (brewblox.field).stored = true ];

  uint32 analogDevice = 2 [
    (brewblox.field).objtype = AnalogArrayInterface,
    (brewblox.field).stored = true
  ];
  uint32 analogChannel = 3
      [ (brewblox.field).stored = true, (nanopb).int_size = IS_8 ];

  sint32 value = 4 [
    (brewblox.field).unit = Celsius,
    (brewblox.field).scale = 4096,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  GpioModule.AnalogSensorType detected = 6 [ (brewblox.field).readonly = true ];
  TempSensorAnalogSpec spec = 7 [ (brewblox.field).stored = true ];

  sint32 resistance = 8 [
    (brewblox.field).unit = Ohm,
    (brewblox.field).scale = 16384,
    (brewblox.field).logged = true,
    (brewblox.field).readonly = true,
    (brewblox.field).omit_if_zero = true,
    (nanopb).int_size = IS_32
  ];

  sint32 spec_r0 = 9 [
    (brewblox.field).unit = Ohm,
    (brewblox.field).scale = 16384,
    (brewblox.field).logged = true,
    (brewblox.field).omit_if_zero = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  sint32 spec_a = 10 [
    (brewblox.field).scale = 268435456,
    (brewblox.field).logged = true,
    (brewblox.field).omit_if_zero = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  sint32 spec_b = 11 [
    (brewblox.field).scale = 2199023255552,
    (brewblox.field).logged = true,
    (brewblox.field).omit_if_zero = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  sint32 spec_c = 12 [
    (brewblox.field).scale = 144115188075855872,
    (brewblox.field).logged = true,
    (brewblox.field).omit_if_zero = true,
    (brewblox.field).readonly = true,
    (nanopb).int_size = IS_32
  ];

  sint32 spec_r0_override = 13 [
    (brewblox.field).unit = Ohm,
    (brewblox.field).scale = 16384,
    (brewblox.field).logged = true,
    (brewblox.field).omit_if_zero = true,
    (nanopb).int_size = IS_32
  ];

  sint32 spec_a_override = 14 [
    (brewblox.field).scale = 268435456,
    (brewblox.field).logged = true,
    (brewblox.field).omit_if_zero = true,
    (nanopb).int_size = IS_32
  ];

  sint32 spec_b_override = 15 [
    (brewblox.field).scale = 2199023255552,
    (brewblox.field).logged = true,
    (brewblox.field).omit_if_zero = true,
    (nanopb).int_size = IS_32
  ];

  sint32 spec_c_override = 16 [
    (brewblox.field).scale = 144115188075855872,
    (brewblox.field).logged = true,
    (brewblox.field).omit_if_zero = true,
    (nanopb).int_size = IS_32
  ];
};

