#!/usr/bin/env node
/**
 * Generates ts/spark-block-types.ts and ts/spark-block-enums.ts from proto/.
 *
 * The .proto files are the source of truth. The custom options declared in
 * brewblox.proto (unit, objtype, readonly, datetime, hexstr, ...) carry the
 * information that the TypeScript types encode by convention (Quantity, Link,
 * Readonly<>, DateString, ...). Every FieldOpts option is either mapped to a
 * type in fieldType() or listed there as deliberately ignored, with the
 * reason, so a maintainer can tell a forgotten option from an irrelevant one.
 * Everything the proto files cannot express is
 * kept in the small, commented tables below. Anything not covered by a rule or
 * a table entry is an error, so a proto change that needs a new convention
 * fails loudly instead of producing a quietly wrong type.
 *
 * Usage: yarn generate [--allow-region-removal]
 *
 * The '// #region Name' markers are a documentation contract: the docs site
 * includes them verbatim. The generator refuses to drop a region that exists
 * in the committed file unless --allow-region-removal is passed.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';
import protobuf from 'protobufjs';

const repoDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const protoDir = path.join(repoDir, 'proto');
const tsDir = path.join(repoDir, 'ts');
const allowRegionRemoval = process.argv.includes('--allow-region-removal');

const HEADER = `// This file is generated by scripts/generate-ts.mjs from proto/*.proto.
// Do not edit by hand: run \`yarn generate\` in brewblox-proto instead.
`;

// ---------------------------------------------------------------------------
// Configuration: everything the proto files cannot express.
// Each entry explains why it exists. Keep this section small.
// ---------------------------------------------------------------------------

// Block types that the UI treats as system blocks (one instance, not user
// created). Only exists in TS. Every entry must be an emitted Block objtype or
// a legacy block type (below).
const SYSTEM_BLOCK_TYPES = [
  'DisplaySettings',
  'SysInfo',
  'TouchSettings',
  'WiFiSettings',
  'Spark2Pins',
  'Spark3Pins',
  'GpioModule',
];

// Controlbox-era block types that have no proto message. The UI still
// registers features for them and the docs include their regions, so they are
// emitted as verbatim fragments (LEGACY_BLOCK_FRAGMENTS) and included in
// BlockType. Candidates for removal in a later UI sweep.
const LEGACY_BLOCK_TYPES = [
  'DeprecatedObject',
  'InactiveObject',
  'TouchSettings',
];

// Curated subset of the brewblox.BlockType interface values (1..255) exposed
// to the UI. No rule reproduces it: StoredAnalogInterface is implemented but
// absent, IoModuleInterface is referenced nowhere but present.
const BLOCK_INTF_TYPES = [
  'Any',
  'ProcessValueInterface',
  'TempSensorInterface',
  'SetpointSensorPairInterface',
  'ActuatorAnalogInterface',
  'ActuatorDigitalInterface',
  'BalancerInterface',
  'MutexInterface',
  'OneWireBusInterface',
  'OneWireDeviceInterface',
  'IoModuleInterface',
  'IoArrayInterface',
  'IoClaimerInterface',
  'AnalogArrayInterface',
  'AnalogClaimerInterface',
  'DS2408Interface',
  'EnablerInterface',
  'ClaimableInterface',
  'DigitalInterface',
];

// TS names for proto messages whose short name is ambiguous or historical.
// Default: the proto short name.
const MESSAGE_RENAMES = {
  'blox.GpioModule.Channel': 'GpioModuleChannel',
  'blox.GpioModule.Status': 'GpioModuleStatus',
  'blox.GpioModule.AnalogChannel': 'AnalogModuleChannel',
  'blox.DisplaySettings.Widget': 'DisplaySlot',
  'blox.SetpointProfile.Point': 'Setpoint',
};

// TS names for proto enums whose short name is ambiguous or historical.
// Default: the proto short name.
const ENUM_RENAMES = {
  'blox.GpioModule.DeviceType': 'GpioDeviceType',
  'blox.GpioModule.ErrorFlags': 'GpioErrorFlags',
  'blox.ActuatorLogic.Result': 'LogicResult',
  'blox.ActuatorLogic.DigitalOperator': 'DigitalCompareOp',
  'blox.ActuatorLogic.AnalogOperator': 'AnalogCompareOp',
  'blox.SysInfo.TemperatureUnit': 'DisplayTempUnit',
  'blox.SysInfo.Platform': 'SparkPlatform',
  'blox.DS2408.PinConnectMode': 'DS2408ConnectMode',
  'blox.Spark2Pins.Hardware': 'Spark2Hardware',
  'blox.WiFiSettings.Security': 'WifiSecurityType',
  'blox.WiFiSettings.Cipher': 'WifiCipherType',
};

// Messages referenced by more than one block, and the interface blocks, live in
// their own regions in this fixed order. Listed messages are emitted in the
// listed order. Any reachable message with more than one owning block that is
// not listed here is an error.
const SHARED_REGIONS = [
  {
    region: 'IoChannel',
    messages: ['blox.IoArray.IoChannel'],
    interfaces: ['IoArrayInterface', 'IoClaimerInterface'],
  },
  {
    region: 'AnalogChannel',
    messages: ['blox.GpioModule.AnalogChannel'],
    interfaces: ['AnalogArrayInterface', 'AnalogClaimerInterface'],
  },
  { region: 'EnablerInterfaceBlock', interfaces: ['EnablerInterface'] },
  { region: 'ClaimableInterfaceBlock', interfaces: ['ClaimableInterface'] },
  {
    region: 'AnalogConstraints',
    // AnalogConstraintBase is a TS-only helper (used once in the UI).
    prefix: `export interface AnalogConstraintBase {
  enabled: boolean;
  limiting: Readonly<boolean>;
}
`,
    messages: [
      'blox.Constraints.ValueConstraint',
      'blox.Constraints.BalancedConstraint',
      'blox.Constraints.AnalogConstraints',
    ],
  },
  {
    region: 'DigitalConstraints',
    // DigitalConstraintBase is a TS-only helper (used once in the UI).
    prefix: `export interface DigitalConstraintBase {
  enabled: boolean;
  limiting: Readonly<boolean>;
  remaining: Readonly<Quantity>;
}
`,
    messages: [
      'blox.Constraints.DurationConstraint',
      'blox.Constraints.MutexedConstraint',
      'blox.Constraints.DigitalConstraints',
    ],
  },
];

// Interface blocks: `XInterfaceBlock extends Block { data: {...} }` for the
// proto interfaces the UI casts to. Only 6 of the 29 proto interfaces have one
// and the field subset is curated, so the fields are listed here. The field
// type is derived from the implementors ((brewblox.msg).impl): every
// implementor must have the field; if they agree the shared type is used, if
// they only agree after dropping Readonly that is used, otherwise the type
// must be declared here (null = derive).
const INTERFACE_BLOCKS = {
  EnablerInterface: { fields: { enabled: null } },
  ClaimableInterface: { fields: { claimedBy: null, settingMode: null } },
  IoArrayInterface: {
    // GpioModule has GpioModuleChannel[]; widen to the base channel type.
    fields: { channels: 'IoChannel[]' },
  },
  IoClaimerInterface: { fields: { hwDevice: null, channel: null } },
  AnalogArrayInterface: {
    // GpioModule.Block lacks `impl = AnalogArrayInterface` in the proto
    // although TempSensorAnalog.analogDevice links to it. Assume it until the
    // proto is fixed (that changes proto_sha, so it waits for a firmware
    // release).
    assumedImplementors: ['blox.GpioModule.Block'],
    // GpioModule has Readonly<AnalogModuleChannel[]>; declare the mutable
    // array so existing casts keep working.
    fields: { analogChannels: 'AnalogModuleChannel[]' },
  },
  AnalogClaimerInterface: {
    fields: { analogDevice: null, analogChannel: null },
  },
};

// Message types whose fields extend another message in TS. The generator
// asserts that every base field exists in the derived message with the same
// type (ignoring Readonly). Fields are still emitted in full.
const EXTENDS = {
  'blox.GpioModule.Channel': 'blox.IoArray.IoChannel',
};

// Fields whose API type differs from the proto because the service codec
// converts them. Overridden fields are not traversed for reachability.
const FIELD_TYPE_OVERRIDES = {
  // sequence.py converts each Instruction message to/from a line of text.
  'blox.Sequence.Block.instructions': 'string[]',
};

// Fields skipped entirely: the deprecated migration submessages are never set
// by the firmware, and the TS Deprecated* constraint types (verbatim below)
// describe old datastore content rather than these messages.
const SKIPPED_FIELDS = new Set([
  'blox.ActuatorAnalogMock.Block.constrainedBy',
  'blox.ActuatorOffset.Block.constrainedBy',
  'blox.ActuatorPwm.Block.constrainedBy',
  'blox.FastPwm.Block.constrainedBy',
  'blox.DigitalActuator.Block.constrainedBy',
  'blox.MotorValve.Block.constrainedBy',
]);

// Singular submessage fields are required by default (the firmware always
// sets block-level submessages). The members of the constraint collections
// are chosen by the user, and json_format omits unset submessages.
const OPTIONAL_SUBMESSAGE_FIELDS = new Set([
  'blox.Constraints.AnalogConstraints.min',
  'blox.Constraints.AnalogConstraints.max',
  'blox.Constraints.AnalogConstraints.balanced',
  'blox.Constraints.DigitalConstraints.minOff',
  'blox.Constraints.DigitalConstraints.minOn',
  'blox.Constraints.DigitalConstraints.delayedOff',
  'blox.Constraints.DigitalConstraints.delayedOn',
  'blox.Constraints.DigitalConstraints.mutexed',
]);

// `bitfield = true` only says "this is a bitmask"; it does not name the flag
// enum. Fields listed here get the numeric TS enum instead of `number`.
const BITFIELD_ENUMS = {
  'blox.IoArray.IoChannel.capabilities': 'ChannelCapabilities',
  'blox.GpioModule.Channel.capabilities': 'ChannelCapabilities',
  'blox.GpioModule.Channel.pinsMask': 'GpioPins',
  'blox.GpioModule.Status.pullUpDesired': 'GpioPins',
  'blox.GpioModule.Status.pullUpStatus': 'GpioPins',
  'blox.GpioModule.Status.pullUpWhenActive': 'GpioPins',
  'blox.GpioModule.Status.pullUpWhenInactive': 'GpioPins',
  'blox.GpioModule.Status.pullDownDesired': 'GpioPins',
  'blox.GpioModule.Status.pullDownStatus': 'GpioPins',
  'blox.GpioModule.Status.pullDownWhenActive': 'GpioPins',
  'blox.GpioModule.Status.pullDownWhenInactive': 'GpioPins',
  'blox.GpioModule.Status.overCurrent': 'GpioPins',
  'blox.GpioModule.Status.openLoad': 'GpioPins',
  'blox.GpioModule.Channel.errorFlags': 'GpioErrorFlags',
  'blox.GpioModule.Status.moduleStatus': 'GpioErrorFlags',
  'blox.GpioModule.Status.faultsHistory5m': 'GpioErrorFlags',
  'blox.GpioModule.Status.faultsHistory60m': 'GpioErrorFlags',
};

// Numeric (bit flag) TS enums generated from a proto enum. String enums are
// the default; these are used with bitwise operators in the UI.
const NUMERIC_ENUMS = {
  ChannelCapabilities: { source: 'blox.IoArray.ChannelCapabilities' },
  GpioErrorFlags: {
    source: 'blox.GpioModule.ErrorFlags',
    // The UI references the short names; renaming them is a small follow-up.
    stripPrefix: 'GPIO_ERR_',
    rename: {
      UNDERVOLTAGE: 'UNDERVOLTAGE_LOCKOUT',
      OVERTEMPERATURE_ERROR: 'OVERTEMPERATURE_SHUTDOWN',
    },
  },
};

// Messages with a multi-member oneof emitted as a union of single-key objects
// instead of a set of optional fields. VarContainer's `empty` member makes
// exactly-one-of the intended semantics.
const ONEOF_UNION_MESSAGES = new Set(['blox.Variables.VarContainer']);

// Enum regions in the documented order. A string entry is a region named
// after its single enum; a pair groups several enums under one region name
// (the docs site includes these names). Enums not listed are appended in
// their own region.
const ENUM_REGION_ORDER = [
  'SettingMode',
  ['GpioModule', ['GpioDeviceType', 'GpioPins', 'GpioErrorFlags']],
  ['AnalogModule', ['AnalogSensorType']],
  'DigitalState',
  'TransitionDurationPreset',
  'ChannelCapabilities',
  'PwmFrequency',
  ['Logic', ['DigitalCompareOp', 'AnalogCompareOp', 'LogicResult']],
  'ReferenceKind',
  'DisplayTempUnit',
  'DS2408ConnectMode',
  'ValveState',
  'FilterChoice',
  'SensorCombiFunc',
  'SequenceStatus',
  'SequenceError',
  'SequenceStoreMode',
  'Spark2Hardware',
  'ResetReason',
  'SparkPlatform',
  'TouchCalibrated',
  ['Wifi', ['WifiSecurityType', 'WifiCipherType']],
  ['DigitalInput', ['ToggleBehavior']],
  ['TempSensorAnalog', ['TempSensorAnalogType', 'TempSensorAnalogSpec']],
];

// ---------------------------------------------------------------------------
// Verbatim fragments: TS-only declarations with no proto counterpart.
// ---------------------------------------------------------------------------

// The API envelope and the typed-field shapes are defined by the service.
const TYPES_PREAMBLE = `// #region Block
export interface Block {
  id: string;
  nid?: number;
  serviceId: string;
  type: BlockType;
  data: { [k: string]: any };
  meta?: { [k: string]: any };
}
// #endregion Block

// #region BloxField
export interface BloxField {
  __bloxtype: string;
}

export interface Quantity extends BloxField {
  __bloxtype: 'Quantity';
  value: number | null;
  unit: string;
  readonly?: boolean;
}

export interface Link extends BloxField {
  __bloxtype: 'Link';
  id: string | null;
  type: BlockOrIntfType | null;
}
// #endregion BloxField

// #region DateString
export type DateString = string;
// #endregion DateString
`;

// Old-style constraint shapes. The UI uses them to migrate stored QuickActions
// widget configs (datastore data, not controller data); their trimmed shapes
// do not match the proto Deprecated* messages.
const DEPRECATED_CONSTRAINTS_FRAGMENT = `// #region DeprecatedConstraints
export interface DeprecatedMinConstraint {
  limiting: Readonly<boolean>;
  min: number;
}

export interface DeprecatedMaxConstraint {
  limiting: Readonly<boolean>;
  max: number;
}

export interface DeprecatedBalancedConstraint {
  limiting: Readonly<boolean>;
  balanced: {
    balancerId: Link;
    granted: number;
  };
}

export interface DeprecatedMinOnConstraint {
  remaining: Readonly<Quantity>;
  minOn: Quantity;
}

export interface DeprecatedMinOffConstraint {
  remaining: Readonly<Quantity>;
  minOff: Quantity;
}

export interface DeprecatedMutexedConstraint {
  remaining: Readonly<Quantity>;
  mutexed: {
    mutexId: Link;
    extraHoldTime: Quantity;
    hasLock: boolean;
  };
}

export interface DeprecatedDelayedOnConstraint {
  remaining: Readonly<Quantity>;
  delayedOn: Quantity;
}

export interface DeprecatedDelayedOffConstraint {
  remaining: Readonly<Quantity>;
  delayedOff: Quantity;
}

export type DeprecatedAnalogConstraint =
  | DeprecatedMinConstraint
  | DeprecatedMaxConstraint
  | DeprecatedBalancedConstraint;

export type DeprecatedDigitalConstraint =
  | DeprecatedMutexedConstraint
  | DeprecatedMinOnConstraint
  | DeprecatedMinOffConstraint
  | DeprecatedDelayedOnConstraint
  | DeprecatedDelayedOffConstraint;

export interface DeprecatedAnalogConstraintsObj {
  constraints: DeprecatedAnalogConstraint[];
}

export interface DeprecatedDigitalConstraintsObj {
  constraints: DeprecatedDigitalConstraint[];
}
// #endregion DeprecatedConstraints
`;

// Block regions for LEGACY_BLOCK_TYPES, slotted into the sorted block order.
const LEGACY_BLOCK_FRAGMENTS = {
  DeprecatedObject: `export interface DeprecatedObjectBlock extends Block {
  type: 'DeprecatedObject';
  data: {
    actualId: Readonly<number>;
  };
}
`,
  InactiveObject: `export interface InactiveObjectBlock extends Block {
  type: 'InactiveObject';
  data: {
    actualType: BlockType;
  };
}
`,
  TouchSettings: `export interface TouchSettingsBlock extends Block {
  type: 'TouchSettings';
  data: {
    calibrated: TouchCalibrated;
    xOffset: number;
    yOffset: number;
    xBitsPerPixelX16: number;
    yBitsPerPixelX16: number;
  };
}
`,
};

// Enums with no proto counterpart. GpioPins names the bit positions of the
// GpioModule pin masks; TouchCalibrated belongs to the legacy TouchSettings.
const VERBATIM_ENUMS = {
  GpioPins: {
    numeric: true,
    body: `export enum GpioPins {
  NONE = 0,
  PIN_1 = 1 << 0,
  PIN_2 = 1 << 1,
  PIN_3 = 1 << 2,
  PIN_4 = 1 << 3,
  PIN_5 = 1 << 4,
  PIN_6 = 1 << 5,
  PIN_7 = 1 << 6,
  PIN_8 = 1 << 7,
}
`,
  },
  TouchCalibrated: {
    numeric: false,
    body: `export const TouchCalibrated = Enum(
  'CALIBRATED_NO',
  'CALIBRATED_YES',
  'CALIBRATED_NEW',
);
`,
  },
};

const ENUMS_HEADER = `import { Enum } from 'typescript-string-enums';

// Note for maintainers:
// If you get the error "'MyEnum' refers to a value, but is used as a type here",
// you need to add a type definition at the bottom of this file:
//
//   export type MyEnum = Enum<typeof MyEnum>;
//
`;

// TS-only enums: the constraint keys and the block/interface union.
const ENUMS_CONSTANTS_FRAGMENT = `export const BlockOrIntfType = Enum(
  ...Enum.values(BlockType),
  ...Enum.values(BlockIntfType),
);

export const DigitalConstraintKey = Enum(
  'mutexed',
  'minOff',
  'minOn',
  'delayedOff',
  'delayedOn',
);

export const AnalogConstraintKey = Enum('min', 'max', 'balanced');

export const AnyConstraintKey = Enum(
  ...Enum.values(DigitalConstraintKey),
  ...Enum.values(AnalogConstraintKey),
);
`;

const ENUMS_CONSTANTS_ALIASES = [
  'BlockIntfType',
  'SystemBlockType',
  'UserBlockType',
  'BlockType',
  'BlockOrIntfType',
  'DigitalConstraintKey',
  'AnalogConstraintKey',
  'AnyConstraintKey',
];

// ---------------------------------------------------------------------------
// Proto loading
// ---------------------------------------------------------------------------

// protobufjs does not bundle google/protobuf/descriptor.proto. This stub
// covers what nanopb.proto and brewblox.proto reference. It is not vendored
// under proto/ because that would change the proto_sha.
const DESCRIPTOR_STUB = `
syntax = "proto2";
package google.protobuf;
message FieldDescriptorProto {
  enum Type {
    TYPE_DOUBLE = 1; TYPE_FLOAT = 2; TYPE_INT64 = 3; TYPE_UINT64 = 4;
    TYPE_INT32 = 5; TYPE_FIXED64 = 6; TYPE_FIXED32 = 7; TYPE_BOOL = 8;
    TYPE_STRING = 9; TYPE_GROUP = 10; TYPE_MESSAGE = 11; TYPE_BYTES = 12;
    TYPE_UINT32 = 13; TYPE_ENUM = 14; TYPE_SFIXED32 = 15; TYPE_SFIXED64 = 16;
    TYPE_SINT32 = 17; TYPE_SINT64 = 18;
  }
}
message FileOptions { extensions 1000 to max; }
message MessageOptions { extensions 1000 to max; }
message FieldOptions { extensions 1000 to max; }
message EnumOptions { extensions 1000 to max; }
message EnumValueOptions { extensions 1000 to max; }
`;

// protobufjs only honours `option allow_alias = true` for values parsed after
// it, while protoc accepts it anywhere in the enum body.
function hoistAllowAlias(src) {
  return src.replace(/enum\s+\w+\s*\{[^}]*\}/g, (body) => {
    if (!/option\s+allow_alias\s*=\s*true\s*;/.test(body)) {
      return body;
    }
    const stripped = body.replace(
      /\s*option\s+allow_alias\s*=\s*true\s*;/g,
      '',
    );
    return stripped.replace('{', '{\n  option allow_alias = true;');
  });
}

async function loadRoot() {
  const root = new protobuf.Root();
  // Every import in the set is a bare filename.
  root.resolvePath = (origin, target) =>
    target.startsWith('google/')
      ? target
      : path.join(protoDir, path.basename(target));
  // The callback must be asynchronous: a synchronous callback makes protobufjs
  // finish after the first nested import and silently drop the rest.
  root.fetch = (filename, cb) => {
    setImmediate(() => {
      if (filename === 'google/protobuf/descriptor.proto') {
        cb(null, DESCRIPTOR_STUB);
        return;
      }
      try {
        cb(null, hoistAllowAlias(fs.readFileSync(filename, 'utf8')));
      } catch (e) {
        cb(e);
      }
    });
  };
  const files = fs
    .readdirSync(protoDir)
    .filter((f) => f.endsWith('.proto'))
    .sort()
    .map((f) => path.join(protoDir, f));
  // keepCase: the service decodes with preserving_proto_field_name, so
  // `spec_r0` must stay `spec_r0`.
  await root.load(files, {
    keepCase: true,
    alternateCommentMode: true,
    preferTrailingComment: true,
  });
  root.resolveAll();
  return root;
}

// ---------------------------------------------------------------------------
// Proto model helpers
// ---------------------------------------------------------------------------

const fq = (obj) => obj.fullName.replace(/^\./, '');

function fail(msg) {
  throw new Error(msg);
}

const warnings = [];
function warn(msg) {
  warnings.push(msg);
}

// `.options` flattens repeated options to the last value; parsedOptions keeps
// every value.
function collectOptions(parsedOptions, key) {
  const out = {};
  for (const entry of parsedOptions ?? []) {
    if (entry[key]) {
      for (const [k, v] of Object.entries(entry[key])) {
        out[k] = k in out ? [].concat(out[k], v) : v;
      }
    }
  }
  return out;
}

function fieldOpts(field) {
  const opts = collectOptions(field.parsedOptions, '(brewblox.field)');
  const nanopb = collectOptions(field.parsedOptions, '(nanopb)');
  opts.ftIgnore = nanopb.type === 'FT_IGNORE';
  return opts;
}

function msgOpts(type) {
  const opts = collectOptions(type.parsedOptions, '(brewblox.msg)');
  opts.impl = [].concat(opts.impl ?? []);
  return opts;
}

function isType(obj) {
  return obj instanceof protobuf.Type;
}

function isEnum(obj) {
  return obj instanceof protobuf.Enum;
}

// A list wrapper is a message whose one field is the repeated or map field
// `items`. The service's API carries the list without the wrapper, so a field
// of a wrapper type takes the list's type; returns the `items` field, or null.
function wrappedItems(field) {
  const target = field.resolvedType;
  if (!target || !isType(target) || field.repeated || field.map) {
    return null;
  }
  const fields = target.fieldsArray;
  if (fields.length !== 1) {
    return null;
  }
  const [items] = fields;
  return items.name === 'items' && (items.repeated || items.map) ? items : null;
}

function* walk(ns) {
  for (const obj of Object.values(ns.nested ?? {})) {
    yield obj;
    if (obj.nested) {
      yield* walk(obj);
    }
  }
}

// First declared name for each value, in declaration order.
function enumMembers(enm) {
  const seen = new Set();
  const members = [];
  for (const [name, value] of Object.entries(enm.values)) {
    if (seen.has(value)) {
      continue;
    }
    seen.add(value);
    members.push({ name, value, comment: enm.comments?.[name] ?? null });
  }
  return members;
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

const SCALAR_TYPES = {
  bool: 'boolean',
  string: 'string',
  double: 'number',
  float: 'number',
  int32: 'number',
  int64: 'number',
  uint32: 'number',
  uint64: 'number',
  sint32: 'number',
  sint64: 'number',
  fixed32: 'number',
  fixed64: 'number',
  sfixed32: 'number',
  sfixed64: 'number',
  bytes: 'string',
};

class Generator {
  constructor(root) {
    this.root = root;
    this.blockTypeEnum = root.lookupEnum('brewblox.BlockType');
    this.messages = new Map(); // fq -> Type, reachable
    this.enums = new Map(); // fq -> Enum, referenced by a field
    this.owners = new Map(); // fq -> Set<objtype>
    this.blocks = []; // { type, objtype, impl }
    this.messageNames = new Map(); // fq -> TS name
    this.enumNames = new Map(); // fq -> TS name
    this.regionOrder = new Map(); // region -> [fq...] in emission order
  }

  // --- names ---------------------------------------------------------------

  messageName(type) {
    const name = fq(type);
    if (this.messageNames.has(name)) {
      return this.messageNames.get(name);
    }
    const opts = msgOpts(type);
    const tsName =
      MESSAGE_RENAMES[name] ??
      (opts.objtype ? `${opts.objtype}Block` : type.name);
    for (const [other, otherName] of this.messageNames) {
      if (otherName === tsName) {
        fail(`TS name collision: ${name} and ${other} both map to ${tsName}`);
      }
    }
    this.messageNames.set(name, tsName);
    return tsName;
  }

  enumName(enm) {
    const name = fq(enm);
    if (!this.enumNames.has(name)) {
      const tsName = ENUM_RENAMES[name] ?? enm.name;
      for (const [other, otherName] of this.enumNames) {
        if (otherName === tsName) {
          fail(`TS name collision: ${name} and ${other} both map to ${tsName}`);
        }
      }
      this.enumNames.set(name, tsName);
    }
    return this.enumNames.get(name);
  }

  // --- reachability --------------------------------------------------------

  collect() {
    const blox = this.root.lookup('blox');
    for (const obj of walk(blox)) {
      if (!isType(obj)) {
        continue;
      }
      const opts = msgOpts(obj);
      if (opts.subtype !== undefined) {
        continue; // test-only messages
      }
      if (!opts.objtype) {
        continue;
      }
      const members = enumMembers(this.blockTypeEnum);
      if (!members.some((m) => m.name === opts.objtype)) {
        warn(
          `${fq(obj)}: objtype ${opts.objtype} is an alias; ` +
            'the service emits the first name for its value',
        );
      }
      this.blocks.push({ type: obj, objtype: opts.objtype, impl: opts.impl });
    }
    this.blocks.sort((a, b) => cmpName(a.objtype, b.objtype));
    const seenObjtypes = new Set();
    for (const block of this.blocks) {
      if (seenObjtypes.has(block.objtype)) {
        fail(`objtype ${block.objtype} is used by more than one Block message`);
      }
      seenObjtypes.add(block.objtype);
      this.visit(block.type, block.objtype, new Set());
    }
  }

  visit(type, owner, stack) {
    const name = fq(type);
    if (!name.startsWith('blox.')) {
      fail(`${name} is outside the blox package`);
    }
    if (Object.keys(type.nested ?? {}).length) {
      fail(
        `${name} has nested declarations; the generator does not flatten them`,
      );
    }
    this.messages.set(name, type);
    if (!this.owners.has(name)) {
      this.owners.set(name, new Set());
    }
    this.owners.get(name).add(owner);
    if (stack.has(name)) {
      return;
    }
    stack.add(name);
    for (const field of this.emittedFields(type)) {
      const target = (wrappedItems(field) ?? field).resolvedType;
      if (!target || FIELD_TYPE_OVERRIDES[`${name}.${field.name}`]) {
        continue;
      }
      if (isEnum(target)) {
        this.enums.set(fq(target), target);
      } else {
        this.visit(target, owner, stack);
      }
    }
    stack.delete(name);
  }

  emittedFields(type) {
    const name = fq(type);
    return type.fieldsArray.filter((field) => {
      const opts = fieldOpts(field);
      if (opts.ignored || opts.ftIgnore) {
        return false;
      }
      if (SKIPPED_FIELDS.has(`${name}.${field.name}`)) {
        return false;
      }
      return true;
    });
  }

  // --- regions -------------------------------------------------------------

  assignRegions() {
    const placed = new Map(); // fq -> region
    for (const shared of SHARED_REGIONS) {
      for (const name of shared.messages ?? []) {
        if (!this.messages.has(name)) {
          fail(
            `SHARED_REGIONS lists ${name}, which is not reachable from any Block`,
          );
        }
        placed.set(name, shared.region);
      }
    }
    for (const [name, owners] of this.owners) {
      if (placed.has(name)) {
        continue;
      }
      if (owners.size !== 1) {
        fail(
          `${name} is referenced by ${[...owners].join(', ')}; ` +
            'add it to SHARED_REGIONS',
        );
      }
      placed.set(name, [...owners][0]);
    }
    this.regions = placed;
  }

  // Helper messages of a block, dependencies first, in field order.
  blockRegionMessages(block) {
    const out = [];
    const seen = new Set();
    const dfs = (type) => {
      const name = fq(type);
      if (seen.has(name)) {
        return;
      }
      seen.add(name);
      for (const field of this.emittedFields(type)) {
        const target = (wrappedItems(field) ?? field).resolvedType;
        if (
          target &&
          isType(target) &&
          !FIELD_TYPE_OVERRIDES[`${name}.${field.name}`]
        ) {
          dfs(target);
        }
      }
      if (this.regions.get(name) === block.objtype) {
        out.push(type);
      }
    };
    dfs(block.type);
    return out;
  }

  // --- field types ---------------------------------------------------------

  // FieldOpts (brewblox.proto) that deliberately have no effect on the
  // TypeScript type. Listed here so nobody mistakes them for forgotten ones:
  // - scale: the wire value is the number multiplied by scale; the service
  //   divides it out before the API, so the TS type stays `number`.
  // - logged / stored: read-mode filters in the service (which fields a
  //   logged or stored read returns); they never change a field's type.
  // - skip_changed: which fields a CHANGED read leaves out; it never changes
  //   a field's type.
  // - ignored (and nanopb FT_IGNORE): handled before this method is reached;
  //   such fields are filtered out in emittedFields().
  // Every other option (unit, objtype, readonly, datetime, hexed, hexstr,
  // ipv4address, bitfield, omit_if_zero, null_if_zero) is mapped below.
  fieldType(type, field) {
    const name = `${fq(type)}.${field.name}`;
    const opts = fieldOpts(field);
    let base;
    const override = FIELD_TYPE_OVERRIDES[name];
    if (override) {
      return { type: override, optional: false, opts };
    }
    const items = wrappedItems(field);
    if (items) {
      const list = this.fieldType(field.resolvedType, items).type;
      return {
        type: opts.readonly ? `Readonly<${list}>` : list,
        optional: false,
        opts,
      };
    }
    if (opts.objtype) {
      base = 'Link';
    } else if (opts.unit) {
      base = 'Quantity';
    } else if (opts.datetime) {
      base = 'DateString | null';
    } else if (opts.hexed || opts.hexstr || opts.ipv4address) {
      base = 'string';
    } else if (field.resolvedType && isEnum(field.resolvedType)) {
      base = this.enumName(field.resolvedType);
    } else if (field.resolvedType) {
      base = this.messageName(field.resolvedType);
    } else if (opts.bitfield) {
      base = BITFIELD_ENUMS[name] ?? 'number';
    } else if (field.type in SCALAR_TYPES) {
      base = SCALAR_TYPES[field.type];
      if (field.type === 'bytes') {
        warn(
          `${name}: bytes without hexstr is base64 on the wire; emitted as string`,
        );
      }
    } else {
      fail(`${name}: unsupported field type ${field.type}`);
    }

    // null_if_zero applies per element: the service converts a scalar
    // field's zero to null, and for a repeated field it converts each zero
    // element to null (`(T | null)[]`, not `T[] | null`). A unit or objtype
    // field is unaffected: the null lands inside Quantity.value / Link.id.
    let element = base;
    if (opts.null_if_zero && !opts.unit && !opts.objtype) {
      if (field.map) {
        fail(`${name}: null_if_zero on a map field has no codec rule`);
      }
      element = `${element} | null`;
    }

    let out = element;
    const union = element.includes('|');
    if (field.map) {
      if (field.keyType !== 'string') {
        fail(`${name}: only string map keys are supported`);
      }
      out = `{ [key: string]: ${element} }`;
    } else if (field.repeated) {
      out = union ? `(${element})[]` : `${element}[]`;
    }
    // A readonly field marked optional is absent while the block reports it
    // invalid, and the service sends null for it. A unit or objtype field
    // is unaffected: the null lands inside Quantity.value / Link.id.
    if (
      opts.readonly &&
      field.options?.proto3_optional &&
      !opts.unit &&
      !opts.objtype
    ) {
      out = `${out} | null`;
    }
    if (opts.readonly) {
      out = `Readonly<${out}>`;
    }

    let optional = false;
    if (opts.omit_if_zero && !field.repeated) {
      optional = true; // the service deletes the key when the value is 0
    }
    if (OPTIONAL_SUBMESSAGE_FIELDS.has(name)) {
      optional = true;
    }
    if (field.partOf && field.partOf.oneof.length > 1) {
      optional = true; // at most one member of the oneof is set
    }
    return { type: out, optional, opts };
  }

  // --- emission: messages --------------------------------------------------

  fieldLines(type) {
    const lines = [];
    let lastOneof = null;
    for (const field of this.emittedFields(type)) {
      const { type: tsType, optional } = this.fieldType(type, field);
      const oneof =
        field.partOf && field.partOf.oneof.length > 1 ? field.partOf : null;
      if (oneof && oneof !== lastOneof) {
        lines.push(`// oneof ${oneof.name}: at most one is set`);
      }
      lastOneof = oneof;
      const comment = field.comment ? field.comment.split('\n') : [];
      if (comment.length > 1) {
        lines.push(...comment.map((c) => `// ${c}`));
      }
      const trailing = comment.length === 1 ? ` // ${comment[0]}` : '';
      lines.push(`${field.name}${optional ? '?' : ''}: ${tsType};${trailing}`);
    }
    return lines;
  }

  emitMessage(type) {
    const name = fq(type);
    const tsName = this.messageName(type);
    const opts = msgOpts(type);
    if (ONEOF_UNION_MESSAGES.has(name)) {
      return this.emitUnionMessage(type);
    }
    if (opts.objtype) {
      return [
        `export interface ${tsName} extends Block {`,
        `type: '${opts.objtype}';`,
        'data: {',
        ...this.fieldLines(type),
        '};',
        '}',
      ].join('\n');
    }
    let extendsClause = '';
    if (EXTENDS[name]) {
      const base = this.messages.get(EXTENDS[name]);
      if (!base) {
        fail(`${name} extends ${EXTENDS[name]}, which is not reachable`);
      }
      this.assertExtends(type, base);
      extendsClause = ` extends ${this.messageName(base)}`;
    }
    return [
      `export interface ${tsName}${extendsClause} {`,
      ...this.fieldLines(type),
      '}',
    ].join('\n');
  }

  assertExtends(type, base) {
    for (const baseField of this.emittedFields(base)) {
      const field = type.fields[baseField.name];
      if (!field) {
        fail(
          `${fq(type)} cannot extend ${fq(base)}: missing field ${baseField.name}`,
        );
      }
      const a = stripReadonly(this.fieldType(base, baseField).type);
      const b = stripReadonly(this.fieldType(type, field).type);
      if (a !== b) {
        fail(
          `${fq(type)} cannot extend ${fq(base)}: ` +
            `${baseField.name} is ${b} but the base has ${a}`,
        );
      }
    }
  }

  emitUnionMessage(type) {
    const tsName = this.messageName(type);
    const fields = this.emittedFields(type);
    const oneofs = Object.values(type.oneofs ?? {}).filter(
      (o) => o.oneof.length > 1,
    );
    if (oneofs.length !== 1) {
      fail(
        `${fq(type)}: oneofStyle union needs exactly one multi-member oneof`,
      );
    }
    const [oneof] = oneofs;
    const common = fields
      .filter((f) => f.partOf !== oneof)
      .map((f) => {
        const { type: t, optional } = this.fieldType(type, f);
        return `${f.name}${optional ? '?' : ''}: ${t};`;
      });
    const members = fields
      .filter((f) => f.partOf === oneof)
      .map((f) => {
        const { type: t } = this.fieldType(type, f);
        return `| { ${[...common, `${f.name}: ${t};`].join(' ')} }`;
      });
    return [`export type ${tsName} =`, ...members, ';'].join('\n');
  }

  // --- emission: interface blocks ------------------------------------------

  implementors(intf) {
    const found = this.blocks
      .filter((b) => b.impl.includes(intf))
      .map((b) => b.type);
    for (const assumed of INTERFACE_BLOCKS[intf].assumedImplementors ?? []) {
      const type = this.messages.get(assumed);
      if (!type) {
        fail(
          `${intf}: assumed implementor ${assumed} is not a reachable Block`,
        );
      }
      if (!found.includes(type)) {
        found.push(type);
      }
    }
    return found;
  }

  emitInterfaceBlock(intf) {
    const config = INTERFACE_BLOCKS[intf];
    if (!config) {
      fail(`no INTERFACE_BLOCKS entry for ${intf}`);
    }
    if (!(intf in this.blockTypeEnum.values)) {
      fail(`${intf} is not a brewblox.BlockType value`);
    }
    const impls = this.implementors(intf);
    if (!impls.length) {
      fail(`${intf} has no implementors`);
    }
    const lines = [];
    for (const [fieldName, declared] of Object.entries(config.fields)) {
      const types = new Set();
      const stripped = new Set();
      for (const impl of impls) {
        const field = impl.fields[fieldName];
        if (!field || !this.emittedFields(impl).includes(field)) {
          fail(`${fq(impl)} implements ${intf} but has no field ${fieldName}`);
        }
        const { type, optional } = this.fieldType(impl, field);
        if (optional) {
          fail(`${fq(impl)}.${fieldName}: interface fields cannot be optional`);
        }
        types.add(type);
        stripped.add(stripReadonly(type));
      }
      let tsType = declared;
      if (!tsType) {
        if (types.size === 1) {
          [tsType] = types;
        } else if (stripped.size === 1) {
          [tsType] = stripped;
        } else {
          fail(
            `${intf}.${fieldName}: implementors disagree (${[...types].join(', ')}); ` +
              'declare the type in INTERFACE_BLOCKS',
          );
        }
      }
      lines.push(`${fieldName}: ${tsType};`);
    }
    return [
      `export interface ${intf}Block extends Block {`,
      'data: {',
      ...lines,
      '};',
      '}',
    ].join('\n');
  }

  // --- emission: files -----------------------------------------------------

  generateTypes(enumNames) {
    const regions = [];
    for (const shared of SHARED_REGIONS) {
      const parts = [];
      if (shared.prefix) {
        parts.push(shared.prefix);
      }
      for (const name of shared.messages ?? []) {
        parts.push(this.emitMessage(this.messages.get(name)));
      }
      for (const intf of shared.interfaces ?? []) {
        parts.push(this.emitInterfaceBlock(intf));
      }
      regions.push(region(shared.region, parts.join('\n\n')));
    }
    regions.push(DEPRECATED_CONSTRAINTS_FRAGMENT);

    const blockRegions = this.blocks.map((block) => ({
      name: block.objtype,
      body: this.blockRegionMessages(block)
        .map((type) => this.emitMessage(type))
        .join('\n\n'),
    }));
    for (const [name, body] of Object.entries(LEGACY_BLOCK_FRAGMENTS)) {
      if (blockRegions.some((r) => r.name === name)) {
        fail(`legacy block ${name} now has a proto message; drop the fragment`);
      }
      blockRegions.push({ name, body });
    }
    blockRegions.sort((a, b) => cmpName(a.name, b.name));
    for (const { name, body } of blockRegions) {
      regions.push(region(name, body));
    }

    // Unplaced reachable messages would be a generator bug.
    for (const name of this.messages.keys()) {
      if (!this.messageNames.has(name)) {
        fail(`${name} is reachable but was not emitted`);
      }
    }

    const body = [TYPES_PREAMBLE, ...regions].join('\n');
    const used = enumNames
      .filter((n) => new RegExp(`\\b${n}\\b`).test(body))
      .sort(cmpName);
    const imports = `import {\n${used.map((n) => `  ${n},`).join('\n')}\n} from './spark-block-enums';\n`;
    return `${HEADER}\n${imports}\n${body}`;
  }

  generateEnums() {
    const emitted = new Map(); // TS name -> { body, numeric }
    for (const [tsName, config] of Object.entries(NUMERIC_ENUMS)) {
      const enm = this.root.lookupEnum(config.source);
      emitted.set(tsName, {
        numeric: true,
        body: emitNumericEnum(tsName, enm, config),
      });
      this.enumNames.set(fq(enm), tsName);
    }
    for (const enm of this.enums.values()) {
      const tsName = this.enumName(enm);
      if (emitted.has(tsName)) {
        continue;
      }
      emitted.set(tsName, {
        numeric: false,
        body: emitStringEnum(tsName, enm),
      });
    }
    for (const [tsName, config] of Object.entries(VERBATIM_ENUMS)) {
      if (emitted.has(tsName)) {
        fail(
          `verbatim enum ${tsName} now has a proto source; drop the fragment`,
        );
      }
      emitted.set(tsName, config);
    }

    const regions = [];
    const placed = []; // TS names in file order
    for (const entry of ENUM_REGION_ORDER) {
      const [name, names] = Array.isArray(entry) ? entry : [entry, [entry]];
      const bodies = names.map((n) => {
        if (!emitted.has(n)) {
          fail(`ENUM_REGION_ORDER lists ${n}, which is not generated`);
        }
        placed.push(n);
        return emitted.get(n).body;
      });
      regions.push(region(name, bodies.join('\n')));
    }
    for (const [name, { body }] of emitted) {
      if (!placed.includes(name)) {
        placed.push(name);
        regions.push(region(name, body));
      }
    }

    const aliases = [
      ...ENUMS_CONSTANTS_ALIASES,
      ...placed.filter((n) => !emitted.get(n).numeric),
    ].map((n) => `export type ${n} = Enum<typeof ${n}>;`);

    const text = [
      HEADER,
      ENUMS_HEADER,
      region('BlockIntfType', this.emitBlockIntfType()),
      region('BlockType', this.emitBlockType()),
      ENUMS_CONSTANTS_FRAGMENT,
      ...regions,
      aliases.join('\n'),
    ].join('\n');
    return { text, names: [...emitted.keys(), ...ENUMS_CONSTANTS_ALIASES] };
  }

  emitBlockIntfType() {
    for (const name of BLOCK_INTF_TYPES) {
      const value = this.blockTypeEnum.values[name];
      if (value === undefined || value < 1 || value > 255) {
        fail(
          `BLOCK_INTF_TYPES: ${name} is not an interface value of brewblox.BlockType`,
        );
      }
    }
    return stringEnum('BlockIntfType', BLOCK_INTF_TYPES);
  }

  emitBlockType() {
    const objtypes = this.blocks.map((b) => b.objtype);
    for (const name of SYSTEM_BLOCK_TYPES) {
      if (!objtypes.includes(name) && !LEGACY_BLOCK_TYPES.includes(name)) {
        fail(`SYSTEM_BLOCK_TYPES: ${name} is not a Block objtype`);
      }
    }
    const user = [...objtypes, ...LEGACY_BLOCK_TYPES]
      .filter((n) => !SYSTEM_BLOCK_TYPES.includes(n))
      .sort(cmpName);
    return [
      stringEnum('SystemBlockType', SYSTEM_BLOCK_TYPES),
      stringEnum('UserBlockType', user),
      `export const BlockType = Enum(
  ...Enum.values(SystemBlockType),
  ...Enum.values(UserBlockType),
);
`,
    ].join('\n');
  }
}

// ---------------------------------------------------------------------------
// Emission helpers
// ---------------------------------------------------------------------------

function cmpName(a, b) {
  const la = a.toLowerCase();
  const lb = b.toLowerCase();
  return la < lb ? -1 : la > lb ? 1 : 0;
}

function stripReadonly(type) {
  const m = /^Readonly<(.*)>$/.exec(type);
  return m ? m[1] : type;
}

function region(name, body) {
  return `// #region ${name}\n${body.trim()}\n// #endregion ${name}\n`;
}

function stringEnum(name, members) {
  const lines = members.map((m) =>
    typeof m === 'string'
      ? `'${m}',`
      : `'${m.name}',${m.comment ? ` // ${m.comment}` : ''}`,
  );
  return `export const ${name} = Enum(\n${lines.join('\n')}\n);\n`;
}

function emitStringEnum(tsName, enm) {
  return stringEnum(tsName, enumMembers(enm));
}

function emitNumericEnum(tsName, enm, config) {
  const lines = enumMembers(enm).map(({ name, value, comment }) => {
    let member = name;
    if (config.stripPrefix) {
      if (!member.startsWith(config.stripPrefix)) {
        fail(`${fq(enm)}.${name} does not start with ${config.stripPrefix}`);
      }
      member = member.slice(config.stripPrefix.length);
    }
    member = config.rename?.[member] ?? member;
    const literal =
      value === 0
        ? '0'
        : Number.isInteger(Math.log2(value))
          ? `1 << ${Math.log2(value)}`
          : String(value);
    return `${member} = ${literal},${comment ? ` // ${comment}` : ''}`;
  });
  return `export enum ${tsName} {\n${lines.join('\n')}\n}\n`;
}

function regionNames(text) {
  return new Set([...text.matchAll(/^\/\/ #region (\S+)/gm)].map((m) => m[1]));
}

async function writeGenerated(file, text) {
  const filepath = path.join(tsDir, file);
  const config = (await prettier.resolveConfig(filepath)) ?? {};
  const formatted = await prettier.format(text, {
    ...config,
    parser: 'typescript',
  });
  if (fs.existsSync(filepath)) {
    const missing = [...regionNames(fs.readFileSync(filepath, 'utf8'))].filter(
      (name) => name && !regionNames(formatted).has(name),
    );
    if (missing.length && !allowRegionRemoval) {
      fail(
        `${file}: regions ${missing.join(', ')} would be removed; the docs site ` +
          'includes them. Pass --allow-region-removal if this is intended.',
      );
    }
  }
  fs.writeFileSync(filepath, formatted);
  console.log(`wrote ${path.relative(repoDir, filepath)}`);
}

async function main() {
  const root = await loadRoot();
  const gen = new Generator(root);
  gen.collect();
  gen.assignRegions();
  const enums = gen.generateEnums();
  const types = gen.generateTypes(enums.names);
  await writeGenerated('spark-block-enums.ts', enums.text);
  await writeGenerated('spark-block-types.ts', types);
  for (const w of warnings) {
    console.warn(`warning: ${w}`);
  }
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
